Indentation = "FourSpaces"
NewLineOnOpenBrace = "After"
MaxEmptyLines = 1
SpacesInBrackets = false
IndentPreprocessor = true
PreprocessorIfCreatesNesting = true
VariableCase = "Camel"
FunctionCase = "Camel"
StructCase = "Pascal"
BoolPrefix = "b"
IntPrefix = "i"
